"use client";

import { AnimatePresence } from 'framer-motion';
import Header from "@/components/Header";
import { ScrollArea } from "@/components/ui/scroll-area"
import { Space_Mono } from "next/font/google"; // Import a monospaced font
import "./globals.css";
import PageTransition from '../components/PageTransition'


const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: "--font-space-mono"
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceMono.variable}>
      <ScrollArea className="h-screen w-screen">
        <Header />
        <AnimatePresence mode="wait">
          <PageTransition>
            {children}
          </PageTransition>
        </AnimatePresence>
      </ScrollArea>
      </body>
    </html>
  );
}