import Header from "@/components/Header";
import { Space_Mono } from "next/font/google"; // Import a monospaced font
import "./globals.css";

const spaceMono = Space_Mono({ 
  subsets: ["latin"],
  weight: ['400','700',],
  variable: "--font-spaceMono" 

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceMono.variable}>
        <Header/>
        {children}

      </body>
    </html>
  );
}
